spring.application.name=RewardsApplication
server.port = 8080

spring.profiles.active=dev


Service.CUSTOMER_NOT_FOUND = Customer not found
Service.TRANSACTION_NOT_FOUND = Transactions not found
Service.INVALID_DATE_MONTH = Provide either month or time range
Service.DATES_REQUIRED = Both start date and end date must be provided
Service.INVALID_DATES = start date cannot be after the end date
Service.INVALID_ENDDATEend date cannot be in future

General.EXCEPTION_MESSAGE = Unexpected internal server error
General.EXCEPTION_DETAILS = Request could not be processed due to some issue. Please try again!
General.EXCEPTION_INVALID_PARAM = Check request parameters
General.EXCEPTION_NOT_FOUND = Requested resource not found